services:

  backend:
    depends_on:
      rabbitmq:
        condition: service_healthy 
    profiles: [ all, backend ]
    build: backend
    image: ${CONTAINER_REGISTRY}/${CI_PROJECT_PATH}/backend:${BACKEND_VERSION}
    container_name: ${APP_NAME}-backend
    ports:
      - "8000:8000"
    env_file:
      - .env.local
      - .env.local.secrets

  frontend:
    profiles: [ all, frontend ]
    build: frontend
    image: ${CONTAINER_REGISTRY}/${CI_PROJECT_PATH}/frontend:${FRONTEND_VERSION}
    container_name: ${APP_NAME}-frontend
    ports:
      - "80:5173"
    env_file:
      - .env.local
      - .env.local.secrets

  rabbitmq:
    profiles: [ all, rabbitmq ]
    build: rabbitmq
    image: ${CONTAINER_REGISTRY}/${CI_PROJECT_PATH}/rabbitmq:${RABBITMQ_VERSION}
    container_name: ${APP_NAME}-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.local
      - .env.local.secrets
    healthcheck:
      start_period: 15s
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      timeout: 3s
      interval: 5s
      retries: 5
