services:

  backend:
    profiles: [ all, backend ]
    build: backend
    image: ${CONTAINER_REGISTRY}/${CI_PROJECT_PATH}/backend:${BACKEND_VERSION}
    container_name: ${APP_NAME}-backend
    ports:
      - "8001:8001"
    env_file:
      - .env.local

  frontend:
    profiles: [ all, frontend ]
    build: frontend
    image: ${CONTAINER_REGISTRY}/${CI_PROJECT_PATH}/frontend:${FRONTEND_VERSION}
    container_name: ${APP_NAME}-frontend
    ports:
      - "8001:8001"
    env_file:
      - .env.local

  rabbitmq:
    profiles: [ all, rabbitmq ]
    build: rabbitmq
    image: ${CONTAINER_REGISTRY}/${CI_PROJECT_PATH}/rabbitmq:${RABBITMQ_VERSION}
    container_name: ${APP_NAME}-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.loca